### ISSUE TITLE
Monorepo

### ISSUE THREAD

**Issue by socksrust** [animavita/animavita#8]
Move it to monorepo, i suggest using yarn workspaces, heres an example:

http://github.com/fotonTech/golden-stack

**Comment by mauriciomutte** [comment]
If you need it, I can help you with that.

**Comment by wendelfreitas** [comment]
@mauriciomutte if you can, it would be very good to learn

**Comment by jaburcodes** [comment]
i can also help, lemme know how we should approach it.

**Comment by mauriciomutte** [comment]
I opened a PR: #12

**Comment by mauriciomutte** [comment]
@jaburcodes How do you structure ESLint and Prettier in monorepo?

**Comment by jaburcodes** [comment]
same common rules for both packages as all foton devs are fullstack:

https://github.com/FotonTech/golden-stack/blob/master/.eslintrc.js
